### ISSUE TITLE
Trouble installing 

### ISSUE THREAD

**Issue by lenhoy** [CestLaGalere/mobilealerts#6]
New to HA, appreciate the integration! 
I am trying to integrate the MA sensors and have tried to follow the instructions, however I can't seem to find any new entities or anything after a restart.

Running curl with the phone and device ids returns a json response as expected. 
in configuration.yaml I have added `sensor: !include_dir_merge_list sensors/` and added a 'sensors' folder containing a 'mobilealerts.yaml' file with the following:
```
sensor:
  - platform: mobile_alerts
    phone_id: XXXXXX
    devices:
      - device_id: XXXXX
        name: mobilealertsSensor temp
        type: t1
      - device_id: XXXXX
        name: mobilealertsSensor humidity
        type: h
```
The mobile_alerts integration does show up in HACS, but under Devices & Services I can't find anything.

Hope this is the right place to ask, I'd appreciate any help :)
