### ISSUE TITLE
t1 not aviable, but at attribute

### ISSUE THREAD

**Issue by satdj** [CestLaGalere/mobilealerts#7]
Hi

sorry, my english is bad

we have any sensors, there are not possible to read t1 value but at Attibute they are visible

i hope with the idx you can work

idx: 13809 Rain Sensor
idx: 16598673 Temp Sensor
idx: 5529819 Temp/Humi Sensor

**Comment by petrleocompel** [comment]
Can you post your configuration? You can anonymize it (cover device_id, phone_id).
Sadly IDX is not enough.

For "real debug" I kinda need them (I do not own any of these devices) you can privately send them to my email and we can test what is wrong.

**Comment by satdj** [comment]
Hi

sorry for late answare
busy at work.. no free time

```
sensor:
  - platform: mobile_alerts
    phone_id: XXXXXXXXXXX
    devices:
      - device_id: XXXXXXXXXXX
        name: MA.01-Baro-Hygro-Thermo.Temp
        type: t1
      - device_id: XXXXXXXXXXX
        name: MA.01-Baro-Hygro-Thermo.Humi
        type: h
      - device_id: XXXXXXXXXXX
        name: MA.01-Baro-Hygro-Thermo.pres
        type: ap
      - device_id: XXXXXXXXXXX
        name: MA.01-Baro-Hygro-Thermo.lbat
        type: lb

      - device_id: XXXXXXXXXXX
        name: MA.01a.Temp
        type: t1
      - device_id: XXXXXXXXXXX
        name: MA.01a.Humi
        type: h
      - device_id: XXXXXXXXXXX
        name: MA.01a.lbat
        type: lb

      - device_id: XXXXXXXXXXX
        name: MA.02.wind
        type: ws
      - device_id: XXXXXXXXXXX
        name: MA.02.boee
        type: wg
      - device_id: XXXXXXXXXXX
        name: MA.02.boee
        type: wd
      - device_id: XXXXXXXXXXX
        name: MA.02.lbat
        type: lb

      - device_id: XXXXXXXXXXX
        name: MA.03.regen
        type: r
      - device_id: XXXXXXXXXXX
        name: MA.03.regen1
        type: rf
      - device_id: XXXXXXXXXXX
        name: MA.03.regen2
        type: rr
      - device_id: XXXXXXXXXXX
        name: MA.03.temp
        type: t1
      - device_id: XXXXXXXXXXX
        name: MA.03.lbat
        type: lb

      - device_id: XXXXXXXXXXX
        name: MA.04.temp
        type: t1
      - device_id: XXXXXXXXXXX
        name: MA.04.lbat
        type: lb

      - device_id: XXXXXXXXXXX
        name: MA.05.temp
        type: t1
      - device_id: XXXXXXXXXXX
        name: MA.05.humi
        type: h
      - device_id: XXXXXXXXXXX
        name: MA.05.lbat
        type: lb
   
      - device_id: XXXXXXXXXXX
        name: MA.06.temp
        type: t1
      - device_id: XXXXXXXXXXX
        name: MA.06.lbat
        type: lb
     
      - device_id: XXXXXXXXXXX
        name: MA.11.temp
        type: t1
      - device_id: XXXXXXXXXXX
        name: MA.11.humi
        type: h
      - device_id: XXXXXXXXXXX
        name: MA.11.lbat
        type: lb


```

![Bildschirmfoto vom 2023-12-17 11-19-45](https://github.com/CestLaGalere/mobilealerts/assets/46569577/e82c0f55-7e8b-4186-8b96-510adb6d3bb3)
![Bildschirmfoto vom 2023-12-17 11-23-50](https://github.com/CestLaGalere/mobilealerts/assets/46569577/e678eca5-54b4-403c-b55a-44b42cf5ac8d)
![Bildschirmfoto vom 2023-12-17 11-25-49](https://github.com/CestLaGalere/mobilealerts/assets/46569577/ca12a970-6338-4fec-a8da-2ad933082693)

hope this helps
